name: Deploy and Validate Metadata

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  sfdxvalidate:
    name: "Run SFDX Validate"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install SFDX CLI
        uses: sfdx-actions/setup-sfdx@v1

      - name: Install sfdx-git-delta plugin
        run: |
          sfdx plugins:install sfdx-git-delta@3.3.0

      - name: Authenticate to Salesforce
        run: |
          echo "${{ secrets.SFDX_AUTH_URL }}" > authFile.txt
          sfdx auth:sfdxurl:store -f authFile.txt -a occ -d

      - name: Generate metadata delta from pull request
        run: |
          mkdir -p .temp
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git fetch origin main
          sfdx sgd:source:delta --to "HEAD" --from "origin/main" --output .temp --generate-delta

      - name: Deploy metadata on main branch (check-only)
        if: github.ref == 'refs/heads/main'
        run: |
          sfdx project deploy start --manifest .temp/package/package.xml --target-org occ --check-only --wait 10 --verbose
